services:
- type: web
  name: employee-suggester-api
  env: python
  plan: free
  rootDir: employee-suggester
  pythonVersion: 3.11
  buildCommand: |
    pip install --upgrade pip
    pip install -r requirements.txt
  startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT --no-access-log
  envVars:
  - key: EMBED_MODEL
    value: sentence-transformers/all-MiniLM-L6-v2
  - key: ALLOWED_ORIGINS
    value: "*"
  - key: HF_HOME
    value: /opt/render/project/.cache/hf
